add convertation from YUYV to h264, now QGroundControl can see our st…
mavlink/mavlink-camera-manager pull request #369
Opened 2024-03-22 19:52 UTC by DmitriyLugovoy

…ream, fix ssl in Dockerfile, update docker/build_and_run.sh now container can see all our cameras

2024-03-27 18:36 UTC, patrickelectric approved these changes

2024-03-27 20:17 UTC, patrickelectric requested changes

2024-03-27 20:17 UTC, patrickelectric commented on src/stream/pipeline/v4l_pipeline.rs
> +                        " ! capsfilter name={filter_name} caps=video/x-h264,stream-format=avc,alignment=au,width={width},height={height},framerate={interval_denominator}/{interval_numerator}",
I believe that we can accomplish the same thing with decodebin3 here, and letting it taking decision over the encoders. @joaoantoniocardoso what you think ?

2026-05-21 22:30 UTC, joaoantoniocardoso commented
Hi, I'm closing this because it doesn't align with what was discussed in #274. Feel free to participate there. Thanks!

2026-05-21 22:30 UTC, closed without merging